2025-09-25 18:49:26 [INFO] root: Starting data ingestion
2025-09-25 18:49:57 [ERROR] networksecurity: Error occurred in python script [C:\Users\anjali\Desktop\Network_Security_System\networksecurity\components\data_ingestion.py] line [39] \u2192 SSL handshake failed: ac-zd6eruo-shard-00-02.v6pup7x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-zd6eruo-shard-00-00.v6pup7x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-zd6eruo-shard-00-01.v6pup7x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 68d5415e7ad43c3411e93067, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-zd6eruo-shard-00-00.v6pup7x.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-zd6eruo-shard-00-00.v6pup7x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-zd6eruo-shard-00-01.v6pup7x.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-zd6eruo-shard-00-01.v6pup7x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-zd6eruo-shard-00-02.v6pup7x.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-zd6eruo-shard-00-02.v6pup7x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2025-09-25 18:49:57 [ERROR] networksecurity: Error occurred in python script [C:\Users\anjali\Desktop\Network_Security_System\networksecurity\components\data_ingestion.py] line [98] \u2192 Error occurred in python script [C:\Users\anjali\Desktop\Network_Security_System\networksecurity\components\data_ingestion.py] line [39] \u2192 SSL handshake failed: ac-zd6eruo-shard-00-02.v6pup7x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-zd6eruo-shard-00-00.v6pup7x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-zd6eruo-shard-00-01.v6pup7x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 68d5415e7ad43c3411e93067, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-zd6eruo-shard-00-00.v6pup7x.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-zd6eruo-shard-00-00.v6pup7x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-zd6eruo-shard-00-01.v6pup7x.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-zd6eruo-shard-00-01.v6pup7x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-zd6eruo-shard-00-02.v6pup7x.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-zd6eruo-shard-00-02.v6pup7x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2025-09-25 18:49:57 [ERROR] networksecurity: Error occurred in python script [C:\Users\anjali\Desktop\Network_Security_System\main.py] line [15] \u2192 Error occurred in python script [C:\Users\anjali\Desktop\Network_Security_System\networksecurity\components\data_ingestion.py] line [98] \u2192 Error occurred in python script [C:\Users\anjali\Desktop\Network_Security_System\networksecurity\components\data_ingestion.py] line [39] \u2192 SSL handshake failed: ac-zd6eruo-shard-00-02.v6pup7x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-zd6eruo-shard-00-00.v6pup7x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-zd6eruo-shard-00-01.v6pup7x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 68d5415e7ad43c3411e93067, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-zd6eruo-shard-00-00.v6pup7x.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-zd6eruo-shard-00-00.v6pup7x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-zd6eruo-shard-00-01.v6pup7x.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-zd6eruo-shard-00-01.v6pup7x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-zd6eruo-shard-00-02.v6pup7x.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-zd6eruo-shard-00-02.v6pup7x.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
